### ISSUE TITLE
No jar file present.

### ISSUE THREAD

**Issue by krnbatra** [AuthEceSoftEng/DP-CORE#1]
Could you tell how to run the project as there is no jar file present.

**Comment by thdiaman** [comment]
Hello, I added a release zip here https://github.com/AuthEceSoftEng/DP-CORE/releases/tag/v0.1
The file DP-CORE_v0.1.zip includes the jar and certain examples.

**Comment by krnbatra** [comment]
Hi, I've one more doubt when running the jar file there is not any option
of browsing the pattern folder, project folder and result folder, only text
boxes are coming. Could you please explain the reason for this.

I've attached a screenshot of the running jar file.

**Comment by thdiaman** [comment]
I cannot find your attachment. I attach a screenshot where there are browse buttons on the right
![dp-core_screenshot](https://cloud.githubusercontent.com/assets/1620264/24373660/b4990670-133a-11e7-8810-5e713be590e0.png)
Are they not there in your system?

**Comment by krnbatra** [comment]
Here is the screenshot in my PC. I'm running it in Ubuntu 15.10
![screenshot from 2017-03-28 00-32-14](https://cloud.githubusercontent.com/assets/15313524/24373860/72599ac0-1350-11e7-9830-606e8fc28d00.png)

**Comment by thdiaman** [comment]
This probably is due to the UI manager of Ubuntu. I added a new issue for this (see #2), and I will try to resolve it. In the meantime you can use the command line interface https://github.com/AuthEceSoftEng/DP-CORE#executing-in-batch-mode
